version: '3.5'

services:
  server:
    image: rddt-server
    container_name: server
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    volumes:
      - ./server:/server

  client:
    image: rddt-client
    container_name: client
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    volumes:
      # anonymous volume needed to prevent overriding of the node modules directory
      - /client/node_modules
      - ./client:/client
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
